name: "Prod Deploy"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: prod
      destroy: "true"
      aws-assume-role-arn: "arn:aws:iam::828692866750:role/isitics-github-actions-tf"
      aws-region: "us-east-1"
      aws-statefile-s3-bucket: "s3-erik-tf/autoscaling-app/terraform.tfstate"